# Generated by Django 6.0.1 on 2026-02-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_caracteristica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('icone', models.CharField(choices=[('lni-package', 'Caixa'), ('lni-star', 'Estrela'), ('lni-drop', 'Gota')], max_length=13, verbose_name='Icone')),
                ('servico', models.CharField(choices=[('PRO', 'Pro'), ('PLUS', 'Plus'), ('PREMIUM', 'Premium')], max_length=10, verbose_name='Serviço')),
                ('usuario', models.IntegerField(verbose_name='Quantidade de usuários')),
                ('armazenamento', models.IntegerField(verbose_name='Armazenamento')),
                ('atendimento', models.CharField(choices=[('Email support', 'Suporte por e-mail'), ('Priority email support', 'Suporte priotário por e-mail'), ('24/7 support', 'Suporte 24/7 por e-mail')], max_length=30, verbose_name='Atendimento')),
            ],
            options={
                'verbose_name': 'Preço',
                'verbose_name_plural': 'Preços',
            },
        ),
    ]
