# Generated by Django 6.0.1 on 2026-02-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='preco',
            name='preco',
            field=models.IntegerField(default=0, verbose_name='Preço'),
        ),
    ]
