# Generated by Django 6.0.1 on 2026-02-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_preco_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preco',
            name='atendimento',
            field=models.CharField(choices=[('Suporte por e-mail', 'e-mail'), ('Priority email support', 'Suporte priotário por e-mail'), ('Atendimento 24 horas', 'Suporte 24/7 por e-mail')], max_length=30, verbose_name='Atendimento'),
        ),
    ]
