# Generated by Django 6.0.1 on 2026-02-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_preco_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preco',
            name='atendimento',
            field=models.CharField(choices=[('Atendimento por e-mail', 'Atendimento por e-mail'), ('Atendimento priotário por e-mail', 'Atendimento priotário por e-mail'), ('Atendimento 24 horas', 'Atendimento 24 horas/dia')], max_length=35, verbose_name='Atendimento'),
        ),
    ]
